using UnityEngine;
using System.Collections.Generic;

public class DWBattleLane : Singleton<DWBattleLane>
{
	public float AttackDragStartDistance;
	public float HologramDisappearDelay;
	public GameObject EnvironmentObj;
	public GameObject BoardObj;
	public GameObject BoardHologram;
	public Transform P1CharacterPos;
	public Transform P2CharacterPos;
	public Transform[] LaneObjParents;
	public Transform DeployObjParent;
	public GameObject LaneObjectPrefab;
	public GameObject DeployVFXPrefab;
	public GameObject DragIndicatorPrefab;
	public Transform TargetIndicatorsParent;
	public CardPrefabScript CurrentCard;
	public DWBattleLaneObject CurrentActionTarget;
	public GameObject RedDeathPrefab;
	public GameObject GreenDeathPrefab;
	public GameObject BlueDeathPrefab;
	public GameObject PurpleDeathPrefab;
	public GameObject YellowDeathPrefab;
	public GameObject SoftCurrencyDropPrefab;
	public GameObject SocialCurrencyDropPrefab;
	public GameObject HardCurrencyDropPrefab;
	public GameObject DropLabelPrefab;
	public GameObject VanishFXAfterDeath;
	public Material CreatureDeathMaterial;
	public List<DWBattleLootObject> CurrentBattleLootInventoryObjects;
	public List<DWBattleLootObject> CurrentBattleLootCurrencyObjects;
	public Transform DragArrowTransform;
	public Transform DragArrowHeadTransform;
	public Transform DragArrowBodyTransform;
	public MeshFilter DragArrowMesh;
	public float DragArrowAnimateSpeed;
	public float DragArrowTextureScale;
	public float DragArrowCurveExponent;
	public float DragArrowStartOffset;
	public float DragArrowVerticalOffset;
	public float DragArrowLengthOffset;
	public float DragArrowHeadHighestAngle;
	public float DragArrowHeadLowestAngle;
	public float DragArrowAiSpacing;
	public Color ValidTargetColor;
	public Color InvalidTargetColor;
	public bool LootCollectAuto;
	public float DeathRepositionTime;
	public float CreatureOffsetX;
	public float Amplitude;
	public float CreatureSpacing;
	public float MinimumCreatureWidth;
	public float MinCreatureHeight;
	public int DebugIgnoreCreaturesInCam;
	public float MoveScaledUpCreaturesBackFactor;
	public bool UpdateCreaturePosition;
	public bool EnableFreeCam;
	public float FreeCamSensitivity;
	public float FreeCamSnapSpeed;
	public float FreeCamMinHeight;
	public float FreeCamMaxHeight;
}
